accounts/urls.py
from django.urls import include, path

from rest_framework import routers

from allauth.account.views import LogoutView

from .api.viewsets import UserViewSet

from .views import (
    ClientSignUpView,
    SitterSignUpView,
    UserLoginView,
    UserProfileView,
)


app_name = 'accounts'

router = routers.SimpleRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    # ex: /accounts/login/
    path(r'login/', UserLoginView.as_view(), name='login'),

    # ex: /accounts/logout/
    path(r'logout/', LogoutView.as_view(), name='logout'),

    # ex: /accounts/client_signup/
    path(r'client_signup/', ClientSignUpView.as_view(), name='client_signup'),

    # ex: /accounts/sitter_signup/
    path(r'sitter_signup/', SitterSignUpView.as_view(), name='sitter_signup'),

    # ex: /accounts/profile/
    path(r'profile/', UserProfileView.as_view(), name='profile'),

    # ex: /accounts/profile/1/
    path(r'profile/<int:pk>/', UserProfileView.as_view(), name='profile'),

    # API
    path(r'api/', include((router.urls)))
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('offers/', include('offers.urls')),
    path('reviews/', include('reviews.urls')),
    path('pets/', include('pets.urls')),
    path('', include('core.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import SitterListView

app_name = 'core'
urlpatterns = [
    # ex: /
    path('', TemplateView.as_view(template_name='core/index.html'), name='index'),

    # ex: /sitters/
    path('sitters/', SitterListView.as_view(template_name='core/sitters.html'), name='sitters'),
]

reviews/urls.py
from django.urls import path

from .views import (
    ReviewList,
) 


app_name = 'reviews'
urlpatterns = [
    # ex: /reviews/1/
    path('<int:target_id>/', ReviewList.as_view(), name='reviews'),

    # ex: /reviews/1/rating
    path('<int:user_id>/rating/', ReviewList.as_view(), name='reviews_rating'),
]

accounts/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser

from phonenumber_field.modelfields import PhoneNumberField
from guardian.mixins import GuardianUserMixin

from .managers import UserManager, ClientManager, SitterManager


class User(GuardianUserMixin, AbstractUser):
    """Define a model User"""

    objects = UserManager()

    username = None

    email = models.EmailField("Email", unique=True)
    phone_number = PhoneNumberField("Phone number", unique=True)

    image = models.ImageField("Profile image", upload_to='users/', null=True, blank=True)

    is_client = models.BooleanField(
        "Client status",
        default=False,
        help_text="Designates that this user is a Client.",
    )
    is_sitter = models.BooleanField(
        "Sitter status",
        default=False,
        help_text="Designates that this user is a Sitter.",
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone_number',]

    def get_absolute_url(self):
        """Get absolute url of User profile"""
        return reverse('accounts:profile', kwargs={'pk': self.pk})

    def __str__(self):
        return self.email


class ClientMore(models.Model):
    """
    Define a model for User model to provide additional Client-related fields
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="clientmore",
    )


class SitterMore(models.Model):
    """
    Define a model for User model to provide additional Sitter-related fields
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="sittermore",
    )

    description = models.TextField(null=True)


class Client(User):
    """Proxy User model to implement Client-related functionality"""
    objects = ClientManager()

    def save(self, *args, **kwargs):
        if not self.id:
            self.is_client = True
        return super().save(*args, **kwargs)

    class Meta:
        proxy = True


class Sitter(User):
    """Proxy User model to implement Sitter-related functionality"""
    objects = SitterManager()

    def clean(self):
        super().clean()
        if not self.is_client:
            raise ValidationError("Sitter must have is_sitter=True.")

    def save(self, *args, **kwargs):
        if not self.id:
            self.is_sitter = True
        return super().save(*args, **kwargs)

    class Meta:
        proxy = True

business_doggies/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_client = models.BooleanField(default=False)
    is_sitter = models.BooleanField(default=False)


class Sitter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField()

accounts/forms.py
from django import forms
from django.contrib.auth.models import Group

from allauth.account.forms import SignupForm, LoginForm
from allauth.account.adapter import get_adapter
from allauth.account.utils import setup_user_email

from phonenumber_field.formfields import PhoneNumberField

from .models import Client, Sitter
from .services import set_user_type


class UserSignUpForm(SignupForm):
    USER_CLIENT = 0
    USER_SITTER = 1
    USER_CHOICES = (
        (USER_CLIENT, "Client"),
        (USER_SITTER, "Sitter"),
    )

    phone_number = PhoneNumberField(
        widget=forms.TextInput(attrs={'placeholder': "Phone number"}),
        required=True,
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': "First name"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': "First name"})
    )

    user_type = forms.TypedChoiceField(
        choices=USER_CHOICES,
        coerce=int,
        widget=forms.HiddenInput(),
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={'placeholder': "Password"}
        )
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={'placeholder': "Confirm password"}
        )

    def signup(self, request, user):
        user.phone_number = self.cleaned_data['phone_number']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        set_user_type(
            user,
            self.cleaned_data['user_type'] == self.USER_CLIENT,
            self.cleaned_data['user_type'] == self.USER_SITTER
        )

    def save(self, request):
        adapter = get_adapter(request)
        user = adapter.new_user(request)
        adapter.save_user(request, user, self, commit=False)
        self.signup(request, user)
        setup_user_email(request, user, [])
        return user


class UserLoginForm(LoginForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        login_widget = forms.TextInput(
            attrs={
                'placeholder': "E-mail or Phone number",
                'autocomplete': "email",
            }
        )
        login_field = forms.CharField(
            label="Login", widget=login_widget
        )

        self.fields['login'] = login_field

    def user_credentials(self):
        """
        Provides the credentials required to authenticate the user for
        login.
        """
        credentials = {}
        login = self.cleaned_data["login"]
        if self._is_login_email(login):
            credentials["email"] = login
        credentials["phone_number"] = login
        credentials["password"] = self.cleaned_data["password"]
        return credentials

accounts/views.py
from django.views.generic import ListView, View
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

from allauth.account.views import LoginView, SignupView

from reviews.forms import ReviewForm
from pets.forms import PetForm
from offers.forms import MakeOfferForm

from .models import User
from .forms import UserSignUpForm, UserLoginForm


class ClientSignUpView(SignupView):
    """View for registering a User as a Client"""
    form_class = UserSignUpForm
    template_name = 'accounts/signup_client.html'
    initial = {'user_type': form_class.USER_CLIENT}


class SitterSignUpView(SignupView):
    """View for registering a User as a Sitter"""
    form_class = UserSignUpForm
    template_name = 'accounts/signup_sitter.html'
    initial = {'user_type': form_class.USER_SITTER}


class UserLoginView(LoginView):
    """User Authentication View"""
    form_class = UserLoginForm
    template_name = 'accounts/login.html'


class UserProfileView(LoginRequiredMixin, View):
    """View of the User profile"""
    form_review_class = ReviewForm
    form_pet_class = PetForm
    form_offer_class = MakeOfferForm

    template_name = 'accounts/profile.html'

    def get(self, request, **kwargs):
        user = get_object_or_404(
            User,
            pk=kwargs.get('pk', request.user.pk)
        )

        context = {
            'profile': user,
        }

        if user.is_client:
            context['form_review'] = self.form_review_class()
            context['form_pet'] = self.form_pet_class()
        elif user.is_sitter:
            context['form_review'] = self.form_review_class()
            context['form_offer'] = self.form_offer_class()

        return render(request, self.template_name, context)


class SitterListView(LoginRequiredMixin, ListView):
    model = User
    context_object_name = 'sitters'
    paginate_by = 5

    def get_queryset(self):
        queryset = self.model.objects.filter(is_sitter=True)
        return queryset

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}- Log In{% endblock title %}

{% block content %}
    <div class="wrapper">
        <div class="container">
            <div><h1 class="login title">We are glad<br/> to see you again</h1></div>
            <form class="login form" method="post" novalidate>
            {% csrf_token %}
                <div class="col-12 p-0 {% if form.login.errors %}error_field{% endif %}">
                    {{ form.login }}
                    {% if form.login.errors %}
                        <div class="text-danger small mb-0 pb-0 mt-2">
                            {{ form.login.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12 p-0 {% if form.password.errors %}error_field{% endif %}">
                    {{ form.password }}
                    {% if form.password.errors %}
                        <div class="text-danger small mb-0 pb-0 mt-2">
                            {{ form.password.errors }}
                        </div>
                    {% endif %}
                </div>
                {% if form.non_field_errors %}
                    <div class="text-danger small mb-0 pb-0 mt-4">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <button type="submit" class="login login_btn">Log In</button>
            </form>
            <div class="login underbutton position-relative">
                <span>Don't have an account? </span><a href="{% url 'core:index' %}" class="login signup_btn stretched-link">Sign Up</a>
            </div>      
        </div>
    </div>
{% endblock content %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% load static %}

{% block title %} - {{profile.first_name}} {{profile.last_name}}{% endblock title %}

{% block name %}   
  {% if user == profile %}         
    <a href="{% url 'accounts:logout' %}" class="nav-link logout-link">Log Out</a>
  {% else %}
    <a href="{% url 'accounts:profile' %}" class="nav-link {% if user.is_client %}client-link{% elif user.is_sitter %}sitter-link{% elif user.is_superuser %}admin-link{% endif %}">
      {% if user.get_full_name %}
        {{ user.get_full_name }}
      {% else %}
        {{ user.email }}
      {% endif %}
    </a>
  {% endif %}
{% endblock name %}

{% block content %}
<div class="container mt-5">
  <div>
    <div class="description position-relative">

      <div class="d-flex">
        <div class="avatar mt-5 shadow position-relative" style="background-image: url({% if profile.image %}{{ profile.image.url }}{% else %}{% static 'img/default-avatar.png' %}{% endif %});">
          {% if user == profile %}
            <button type="button" class="btn close align-self-start stretched-link mt-2 mr-2 edit-avatar" name="button" aria-label="Edit" data-toggle="modal" data-target="">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="white" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
              </svg>
            </button>
          {% endif %}
        </div>
        <div class="description_wrapper ml-5">
          <div class="header_description_wrapper">
            <div class="d-flex align-items-center">
              <p class="{% if profile.is_client %}name-client{% elif profile.is_sitter %}name-sitter{% elif profile.is_superuser %}name-admin{% endif %}">
                {% if profile.get_full_name %}
                  {{ profile.get_full_name }}
                {% else %}
                  {{ profile.email }}
                {% endif %}
              </p>
              {% if user == profile %}
                <button class="{% if profile.is_client %}edit-client{% elif profile.is_sitter %}edit-sitter{% elif profile.is_superuser %}edit-admin{% endif %} btn">Edit</button>
              {% elif user.is_client and profile.is_sitter %}
                <button class="edit-sitter btn" data-toggle="modal" data-target="#hireModal">Hire</button>
                <div class="modal custom hire fade" id="hireModal" tabindex="-1" role="dialog" aria-labelledby="hireModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-title pl-4" id="hireModalLabel">Hire {{ profile.get_full_name }}</div>
                      <div class="modal-body">
                        <div class="row">
                          <div class="col-6">
                            <div class="row avatar"></div>
                          </div>
                          <div class="col-6 p-3">
                            <form class="modal-form h-100 d-flex flex-column justify-content-between" method="post">
                              {% csrf_token %}
                                {{ form_offer.as_p }}
                                <button class="send_btn mt-3" value="{{ profile.pk }}" type="submit" data-dismiss="modal">Send</button>
                              <script>$('.send_btn.hire').on('click', send_offer);</script>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              {% endif %}
            </div>
          </div>
          <p class="small">E-mail</p>
          <p>{{ profile.email }}</p>
          <p class="small">Phone Number</p>
          <p>{{ profile.phone_number }}</p>
          {% if profile.is_sitter %}
            {% if profile.sitter.description %}
              <p class="small">Description</p>
              <p>{{ profile.sitter.description }}</p>
            {% elif user == profile %}
              <p class="small">Description</p>
              <p class="text-muted">Add description...</p>
            {% endif %}
          {% endif %}
        </div>
      </div>

      {% if profile.is_client %}
        {% if profile.pets_pets or user == profile %}
          <div class="mt-5">
            <p class="name">Pets</p>
            <div class="d-flex flex-wrap">
              {% for pet in profile.pets_pets %}
                <div>
                  <div class="card pet-card shadow mx-2 my-4">
                    {% if pet.image %}
                      <div class="card-img-top pet-card-img" style="background-image: url({{ pet.image.url }});">
                    {% else %}
                      <div class="card-img-top pet-card-img bg-primary">
                    {% endif %}
                        <button type="button" class="btn close align-self-end stretched-link m-2" name="button" aria-label="Edit" data-toggle="modal" data-target="#edi pet-">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-x" viewBox="0 0 16 16">
                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                        </button>
                      </div>
                    <div class="d-flex flex-column card-body">
                      <h5>{{ pet.name }}</h5>
                      <div class="overflow-auto">
                        {% if pet.description %}
                          <p class="card-text text-muted">{{ pet.description }}</p>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
              {% if user == profile %}
                <div>
                  <div class="card pet-card shadow mx-2 my-4">
                    <button type="button" name="button" class="btn close my-auto stretched-link edit-pet" data-toggle="modal" data-target="#petModal">
                      <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-plus" fill="white" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                      </svg>
                    </button>
                  </div>
                </div>

                <div class="modal custom pet fade" id="petModal" tabindex="-1" role="dialog" aria-labelledby="petModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-title pl-4" id="petModalLabel"><span class="m-auto">Information<br> about your pet</span></div>
                            <div class="modal-body">
                                <form class="modal-form d-flex flex-column align-items-center" method="post">
                                {% csrf_token %}
                                    {{ form_pet.name }}
                                    {{ form_pet.description }}
                                    <div class="form-group">
                                        <label for="inputImage">Choose image</label>
                                        {{ form_pet.image }}
                                    </div>
                                    <button class="send_btn pet mt-3" type="submit">Create</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
              {% endif %}
            </div>
          </div>
        {% endif %}
      {% endif %}

      <div class="reviews mt-5">
        <p class="name mb-4">Reviews about {{ profile.get_short_name }}</p>
        {% if profile.is_client and user != profile and user.is_sitter %}
          <form id="add-review" action="{% url 'reviews:reviews' profile.pk %}">
             {% csrf_token %}
            <div class="d-flex align-items-center">
                {{ form_review.text }}
              <button id="submit-review" val="{{ profile.pk }}" type="submit" class="edit-sitter btn">Send</button>
            </div>
          </form>
        {% elif profile.is_sitter and user != profile and user.is_client %}
          <div class="mb-5">
            <form id="add-review" method="post" action="{% url 'reviews:reviews_rating' profile.pk %}">
              {% csrf_token %}
              <div class="d-flex align-items-center">
                {{ form_review.text }}
                <div>
                  {{ form_review.rating }}
                  <button id="submit-review" val="{{ profile.pk }}" type="submit" class="edit-sitter btn">Send</button>
                </div>
              </div>
            </form>
          </div>
        {% endif %}
        {% for review in profile.reviews_review_recv.all %}
          {% if forloop.counter > 1 %}<hr class="{% if profile.is_client %}hr-client{% elif profile.is_sitter %}hr-sitter{% endif %}" style="width: 50%;" align="left">{% endif %}
          <div class="review d-flex my-4">
            <div class="avatar-review shadow mr-3" style="background-image: url({% if review.author.image %}{{ review.author.image.url }}{% else %}{% static 'img/default-avatar.png' %}{% endif %});"></div>
            <div class="w-100">
              <div class="review_contant_wrapper">
                <div class="name_stars_wrapper">
                  <p><a href="{% url 'accounts:profile' review.author.pk %}">{{ review.author.get_full_name }}</a></p>
                </div>
                <div class="ml-100 data">{{ review.pub_date }}</div>
              </div>
              <p class="comment">{{ review.text }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/accounts/profile_sitter.html
{% extends 'base.html' %}

{% load static %}

{% block title %} - {{ profile.get_full_name }}{% endblock title %}

{% block header %}
  {% if user == profile %}
    <a href="{% url 'core:sitters' %}" class="nav-link">Find Sitter</a>
    <a href="{% url 'accounts:logout' %}" class="nav-link logout-link">Log Out</a>
  {% else %}
    {% if user.is_client %}
        <a href="{% url 'core:sitters' %}" class="nav-link">Find Sitter</a>
        <a href="{% url 'accounts:profile' %}" class="nav-link client-link">{{ user.first_name }} {{ user.last_name }}</a>
    {% elif user.is_sitter %}
        <a href="{% url 'core:sitters' %}" class="nav-link">Find Sitter</a>
        <a href="{% url 'accounts:profile' %}" class="nav-link sitter-link">{{ user.first_name }} {{ user.last_name }}</a>
    {% elif user.is_superuser %}
        <a href="{% url 'admin:index' %}" class="nav-link logout-link">Admin</a>
    {% endif %}
  {% endif %}
{% endblock header %}

{% block hr %}
  <hr class="hr-sitter">
{% endblock hr %}

{% block content %}
<div class="container mt-5">
  <div>
    <div class="description position-relative">
      <div class="d-flex">
        <div class="avatar align-self-center shadow position-relative" style="background-image: url({% if profile.image %}{{ profile.image.url }}{% else %}{% static 'img/default-avatar.png' %}{% endif %});">
          {% if user == profile %}
            <button type="button" class="btn close align-self-start stretched-link mt-2 mr-2" name="button" aria-label="Edit" data-toggle="modal" data-target="">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="white" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
              </svg>
            </button>
          {% endif %}
        </div>
        <div class="description_wrapper ml-5">
          <div class="header_description_wrapper">
            <div class="d-flex align-items-center">
              <p class="name-sitter">{{ profile.get_full_name }}</p>
              {% if user == profile %}
                <button class="edit-sitter btn">Edit</button>
              {% elif user.is_client %}
                <button class="edit-sitter btn" data-toggle="modal" data-target="#hireModal">Hire</button>
              {% endif %}
            </div>
          </div>
          <p class="small">City</p>
          <p>Minsk</p>
          <p class="small">E-mail</p>
          <p>{{ profile.email }}</p>
          <p class="small">Phone Number</p>
          <p>{{ profile.phone_number }}</p>
          <p class="sm">Description</p>
          <p>{{ profile.sitter.description }}</p>
        </div>
      </div>
      
      <div></div>
      <div class="reviews mt-5">
        <p class="name mb-4">Reviews about {{ profile.get_short_name }}</p>
        {% if user != profile and not user.is_sitter %}
        <div class="mb-5">
          <form id="add-review" method="post" action="{% url 'reviews:createrating' profile.pk %}">
          {% csrf_token %}
            <div class="d-flex align-items-center">
                {{ form_review.text }}
                <div>
                  {{ form_review.rating }}
                  <button id="submit-review" val="{{ profile.pk }}" type="submit" class="edit-sitter btn">Send</button>
                </div>
            </div>
          </form>
        </div>
          <script>
            $("#add-review").on("submit", addReviewRating);
            $('#add-review textarea').autoResize();
          </script>
        {% endif %}
        {% for review in profile.reviews_reviewrating_recv.all %}
          {% if forloop.counter > 1 %}<hr class="hr-client" style="width: 50%;" align="left">{% endif %}
          <div class="review">
          <div class="review_contant_wrapper">
            <div class="name_stars_wrapper">
              <p><a href="{% url 'accounts:profile' review.author.pk %}">{{ review.author.get_full_name }}</a> - {{review.rating}}</p>
            </div>
            <div class="data">{{ review.pub_date }}</div>
          </div>
          <p class="comment">{{ review.text }}</p>
          <div class="review_background"></div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% if user != profile and user.is_client %}
<div class="modal custom hire fade" id="hireModal" tabindex="-1" role="dialog" aria-labelledby="hireModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
          <div class="modal-content">
              <div class="modal-title pl-4" id="hireModalLabel">Hire {{ profile.get_full_name }}</div>
              <div class="modal-body">
                  <div class="row">
                      <div class="col-6">
                          <div class="row avatar">
                          </div>
                      </div>
                      <div class="col-6 p-3">
                          <form class="modal-form h-100 d-flex flex-column justify-content-between" method="post">
                          {% csrf_token %}
                              {{ form_offer.as_p }}
                              <button class="send_btn mt-3" value="{{ profile.pk }}" type="submit" data-dismiss="modal">Send</button>
                              <script>$('.send_btn.hire').on('click', send_offer);</script>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  {% endif %}
{% endblock content %}