accounts/urls.py
from django.urls import include, path

from rest_framework import routers

from allauth.account.views import LogoutView

from .api.viewsets import UserViewSet

from .views import (
    ClientSignUpView,
    SitterSignUpView,
    UserLoginView,
    UserProfileView,
)


app_name = 'accounts'

router = routers.SimpleRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    # ex: /accounts/login/
    path(r'login/', UserLoginView.as_view(), name='login'),

    # ex: /accounts/logout/
    path(r'logout/', LogoutView.as_view(), name='logout'),

    # ex: /accounts/client_signup/
    path(r'client_signup/', ClientSignUpView.as_view(), name='client_signup'),

    # ex: /accounts/sitter_signup/
    path(r'sitter_signup/', SitterSignUpView.as_view(), name='sitter_signup'),

    # ex: /accounts/profile/
    path(r'profile/', UserProfileView.as_view(), name='profile'),

    # ex: /accounts/profile/1/
    path(r'profile/<int:pk>/', UserProfileView.as_view(), name='profile'),

    # API
    path(r'api/', include((router.urls)))
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('offers/', include('offers.urls')),
    path('reviews/', include('reviews.urls')),
    path('pets/', include('pets.urls')),
    path('', include('core.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import SitterListView

app_name = 'core'
urlpatterns = [
    # ex: /
    path('', TemplateView.as_view(template_name='core/index.html'), name='index'),

    # ex: /sitters/
    path('sitters/', SitterListView.as_view(template_name='core/sitters.html'), name='sitters'),
]

templates/core/index.html
{% extends 'base.html' %}

{% block link %}
    <link rel="stylesheet" href="../static/css/header.css">
{% endblock link %}

{% block content %}
    <div class="container">
        <div class="content">
            <h1>Web application to manage her employees</h1>
            <div class="button_wrapper d-flex flex-sm-row flex-column justify-content-center mr-auto ml-auto align-items-center">
                <a href="{% url 'accounts:client_signup' %}">
                    <button class="mr-sm-4 client btn btn-light">
                        I’m a client
                    </button>
                </a>
                <a href="{% url 'accounts:sitter_signup' %}">
                    <button class="ml-sm-4 mt-sm-0 mt-4 nanny btn btn-light">
                        I’m a sitter
                    </button>
                </a>
            </div>
        </div>
    </div>
    <div class="offer">
        <div class="container">
          <div class="offer_text">
            <h2>How does it work?</h2>
            <p>
              Hire trustworthy sitters with confidence. Our platform offers the
              easiest, most direct way to find sitter for you. Safe. Secure.
              Privacy Assured. <a href="#">Start now!</a>
            </p>
          </div>
        </div>
      </div>

      <div class="block4">
        <div class="container">
          <div class="webelieve">
            <h2>What we believe</h2>
            <p>
              We developed this simple and accessible platform with the belief
              that it will help to connect the kind and skillful hands of
              sitters with the paws of our smaller brothers.
              <a href="#">Try it now! </a>
            </p>
          </div>
          <div class="counter">
            <div>
              <h3>41 000</h3>
              <span>Registered clients</span>
            </div>
            <div>
              <h3>56 000</h3>
              <span>Registered sitters</span>
            </div>
            <div>
              <h3>5 000</h3>
              <span>Users online</span>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

templates/core/sitters.html
{% extends 'base.html' %}

{% load static %}

{% block title %}- Sitters{% endblock title %}

{% block content %}
    <div class="container mt-5 d-flex flex-wrap justify-content-center">
        {% for sitter in sitters %}
            <div class="p-4 rounded-lg text-light position-relative mb-4 mx-2 sitter-card">
                <div class="media align-items-center">
                    <div class="sitter-img mr-3 shadow" style="background-image: url({% if sitter.image %}{{ sitter.image.url }}{% else %}{% static 'img/default-avatar.png' %}{% endif %});"></div>
                    <div class="media-body mr-3">
                        <h1 class="display-3 font-weight-bold name">{{ sitter.first_name }} {{ sitter.last_name }}</h1>
                        {% if sitter.sitter.description %}
                            <p class="lead">{{ sitter.sitter.description }}</p>
                        {% endif %}
                        <a class="hire-btn stretched-link" href={% url 'accounts:profile' sitter.pk %}></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}