accounts/urls.py
from django.urls import include, path

from rest_framework import routers

from allauth.account.views import LogoutView

from .api.viewsets import UserViewSet

from .views import (
    ClientSignUpView,
    SitterSignUpView,
    UserLoginView,
    UserProfileView,
)


app_name = 'accounts'

router = routers.SimpleRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    # ex: /accounts/login/
    path(r'login/', UserLoginView.as_view(), name='login'),

    # ex: /accounts/logout/
    path(r'logout/', LogoutView.as_view(), name='logout'),

    # ex: /accounts/client_signup/
    path(r'client_signup/', ClientSignUpView.as_view(), name='client_signup'),

    # ex: /accounts/sitter_signup/
    path(r'sitter_signup/', SitterSignUpView.as_view(), name='sitter_signup'),

    # ex: /accounts/profile/
    path(r'profile/', UserProfileView.as_view(), name='profile'),

    # ex: /accounts/profile/1/
    path(r'profile/<int:pk>/', UserProfileView.as_view(), name='profile'),

    # API
    path(r'api/', include((router.urls)))
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('offers/', include('offers.urls')),
    path('reviews/', include('reviews.urls')),
    path('pets/', include('pets.urls')),
    path('', include('core.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import SitterListView

app_name = 'core'
urlpatterns = [
    # ex: /
    path('', TemplateView.as_view(template_name='core/index.html'), name='index'),

    # ex: /sitters/
    path('sitters/', SitterListView.as_view(template_name='core/sitters.html'), name='sitters'),
]

offers/urls.py
from django.urls import path

from .views import (
    OfferListView,
    OfferAnswersListView,
    MakeOfferView,
)
from .views import (
    accept_offer_view,
    decline_offer_view
)


app_name = 'offers'
urlpatterns = [
    # ex: /offers/
    path('', OfferListView.as_view(), name='offers'),

    # ex: /offers/answers
    path('answers/', OfferAnswersListView.as_view(), name='answers'),

    # ex: /offers/1/
    path('<int:sitter_id>/', MakeOfferView.as_view(), name='make'),

    # ex: /offers/1/accept/
    path('accept/<int:offer_id>/', accept_offer_view, name='accept'),

    # ex: /offers/1/decline/
    path('decline/<int:offer_id>/', decline_offer_view, name='decline'),
]

offers/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Offer(models.Model):

    client = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_sent",
        related_query_name="%(app_label)s_%(class)ss",
    )

    sitter = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_recv",
        related_query_name="%(app_label)s_%(class)ss",
    )

    created_datetime = models.DateTimeField(
        auto_now_add=True,
        help_text="Time and date of creation",
    )

    offer_datetime = models.DateTimeField(
        help_text="Time and date when sitter is needed",
    )
    client_address = models.CharField(
        max_length=255,
        help_text="Client address",
    )

    PAYMENT_METHOD_CASH = 0
    PAYMENT_METHOD_CARD = 1
    PAYMENT_METHOD_CHOICES = [
        (PAYMENT_METHOD_CASH, "Cash"),
        (PAYMENT_METHOD_CARD, "Card"),
    ]
    payment_method = models.PositiveSmallIntegerField(
        choices=PAYMENT_METHOD_CHOICES,
        default=PAYMENT_METHOD_CASH,
        help_text="Payment method",
    )

    STATUS_DECLINED = 0
    STATUS_PENDING = 1
    STATUS_ACCEPTED = 2
    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_ACCEPTED, "Accepted"),
        (STATUS_DECLINED, "Declined"),
    )
    status = models.PositiveSmallIntegerField(
        choices=STATUS_CHOICES,
        default=STATUS_PENDING,
        help_text="Status of the offer",
    )

    comment = models.CharField(
        max_length=512,
        null=True
    )

    def __str__(self):
        return "{} - {}".format(self.client, self.sitter)

    def is_finished(self):
        now = timezone.now()
        return now > self.offer_datetime

offers/forms.py
from django import forms

from .models import Offer


class MakeOfferForm(forms.ModelForm):
    offer_datetime = forms.DateTimeInput(attrs={'placeholder': "Date and time"})

    class Meta:
        model = Offer
        fields = ['offer_datetime', 'client_address', 'payment_method', 'comment']
        labels = {
            'offer_datetime': "Date and Time",
            'client_address': "Your address",
            'payment_method': "Payment Method",
        }
        widgets = {
            'client_address': forms.TextInput(attrs={'placeholder': "Your address"}),
            'comment': forms.TextInput(attrs={'placeholder': "Comment"}),
        }
    

offers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model


from guardian.shortcuts import assign_perm
from guardian.decorators import permission_required_or_403

from .models import Offer
from .forms import MakeOfferForm


class OfferListView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = 'offers.view_offer'
    template_name = 'offers/offers.html'

    def get(self, request, *args, **kwargs):
        user = self.request.user
        context = {
            'offers': None,
        }
        if user.has_perm('offers.add_offer'):
            context['offers'] = Offer.objects.filter(
                client=self.request.user,
                status=Offer.STATUS_PENDING
            ).order_by('created_datetime')

        elif user.has_perm('offers.change_offer'):
            context['offers'] = Offer.objects.filter(
                sitter=self.request.user,
                status=Offer.STATUS_PENDING
            ).order_by('created_datetime')
        
        return render(self.request, self.template_name, context)


class OfferAnswersListView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = 'offers.view_offer'
    template_name = 'offers/answers.html'

    def get(self, request, *args, **kwargs):
        user = self.request.user
        context = {
            'offers': None,
        }
        if user.has_perm('offers.add_offer'):
            context['offers'] = Offer.objects.filter(
                client=self.request.user,
                status__in=[Offer.STATUS_ACCEPTED, Offer.STATUS_DECLINED]
            ).order_by('status')

        elif user.has_perm('offers.change_offer'):
            context['offers'] = Offer.objects.filter(
                sitter=self.request.user,
                status__in=[Offer.STATUS_ACCEPTED, Offer.STATUS_DECLINED]
            ).order_by('status')
        
        return render(self.request, self.template_name, context)


class MakeOfferView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = 'offers.add_offer'
    template_name = 'offers/form.html'
    form_class = MakeOfferForm
    success_url = reverse_lazy('list')

    def get(self, request, sitter_id, *args, **kwargs):
        get_object_or_404(get_user_model(), pk=sitter_id)
        form = self.form_class()
        context = {
            'form': form,
            'sitter_id': sitter_id,
        }
        return render(request, self.template_name, context)

    def post(self, request, sitter_id, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            offer = form.save(commit=False)
            offer.client = request.user
            offer.sitter = get_object_or_404(get_user_model(), pk=sitter_id)
            offer.save()

            # Apply permissions
            assign_perm('offers.change_offer', offer.client, offer)

            return redirect(self.success_url)

        context = {
            'form': form,
            'sitter_id': sitter_id,
        }
        return render(request, self.template_name, context)


@login_required
@permission_required_or_403('offers.change_offer')
def accept_offer_view(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)
    if not request.user.pk == offer.sitter.pk:
        raise PermissionDenied
    offer.status = Offer.STATUS_ACCEPTED
    offer.save()
    return redirect(reverse_lazy('offers:offers'))


@login_required
@permission_required_or_403('offers.change_offer')
def decline_offer_view(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)
    if not request.user.pk == offer.sitter.pk:
        raise PermissionDenied
    offer.status = Offer.STATUS_DECLINED
    offer.save()
    return redirect(reverse_lazy('offers:offers'))

templates/offers/answers.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    {% for offer in offers %}
        {% if forloop.counter > 1 %}<hr class="{% if user.is_client %}hr-client{% else %}hr-sitter{% endif %}" style="width: 50%;" align="left">{% endif %}
        <div class="review">
          <div class="review_contant_wrapper">
            <div class="name_stars_wrapper">
              {% if user.is_client %}
              <p class="small"><a href="{% url 'accounts:profile' offer.sitter.pk %}">{{ offer.sitter.get_full_name }}</a></p>
            {% else %}
                <p class="small"><a href="{% url 'accounts:profile' offer.client.pk %}">{{ offer.client.get_full_name }}</a></p>
            {% endif %}
            </div>
            {% if offer.status == 0 %}
            <div class="text-danger">Declined</div>
            {% else %}
            <div class="text-success">Accepted</div>
            {% endif %}
          </div>
          <p class="comment">{% if offer.comment %}{{ offer.comment }}{% endif %}</p>
          <p class="comment">{{ offer.client_address }} - {{ offer.offer_datetime }} - Payment by {{ offer.get_payment_method_display }}</p>
          <div class="review_background"></div>
        </div>
    {% endfor %}
{% endblock content %}

templates/offers/form.html
{% extends 'base.html' %}

{% block content %}
    <form>
    {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"></button>
    </form>
{% endblock content %}

templates/offers/make.html
{% extends 'base.html' %}

{% block content %}
    <form>
    {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"></button>
    </form>
{% endblock content %}

templates/offers/offers.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    {% for offer in offers %}
        {% if forloop.counter > 1 %}<hr class="{% if user.is_client %}hr-client{% else %}hr-sitter{% endif %} " style="width: 50%;" align="left">{% endif %}
        <div class="review">
          <div class="review_contant_wrapper">
            <div class="name_stars_wrapper">
            {% if user.is_client %}
              <p class="small"><a href="{% url 'accounts:profile' offer.sitter.pk %}">{{ offer.sitter.get_full_name }}</a></p>
            {% else %}
                <p class="small"><a href="{% url 'accounts:profile' offer.client.pk %}">{{ offer.client.get_full_name }}</a></p>
            {% endif %}
            </div>
            {% if user.is_client %}
            <div class="text-muted">Pending</div>
            {% else %}
            <div>
              <a class="btn-accept btn btn-success" href="{% url 'offers:accept' offer.pk %}">Accept</a>
              <a class="btn-decline btn btn-outline-danger" href="{% url 'offers:decline' offer.pk %}">Decline</a>
            </div>
            {% endif %}
          </div>
          <p class="comment">{% if offer.comment %}{{ offer.comment }}{% endif %}</p>
          <p class="comment">{{ offer.client_address }}, {{ offer.offer_datetime }}. Payment by {{ offer.get_payment_method_display }}</p>
          <div class="review_background"></div>
        </div>
    {% endfor %}
{% endblock content %}