accounts/urls.py
from django.urls import include, path

from rest_framework import routers

from allauth.account.views import LogoutView

from .api.viewsets import UserViewSet

from .views import (
    ClientSignUpView,
    SitterSignUpView,
    UserLoginView,
    UserProfileView,
)


app_name = 'accounts'

router = routers.SimpleRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    # ex: /accounts/login/
    path(r'login/', UserLoginView.as_view(), name='login'),

    # ex: /accounts/logout/
    path(r'logout/', LogoutView.as_view(), name='logout'),

    # ex: /accounts/client_signup/
    path(r'client_signup/', ClientSignUpView.as_view(), name='client_signup'),

    # ex: /accounts/sitter_signup/
    path(r'sitter_signup/', SitterSignUpView.as_view(), name='sitter_signup'),

    # ex: /accounts/profile/
    path(r'profile/', UserProfileView.as_view(), name='profile'),

    # ex: /accounts/profile/1/
    path(r'profile/<int:pk>/', UserProfileView.as_view(), name='profile'),

    # API
    path(r'api/', include((router.urls)))
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('offers/', include('offers.urls')),
    path('reviews/', include('reviews.urls')),
    path('pets/', include('pets.urls')),
    path('', include('core.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from accounts.views import SitterListView

app_name = 'core'
urlpatterns = [
    # ex: /
    path('', TemplateView.as_view(template_name='core/index.html'), name='index'),

    # ex: /sitters/
    path('sitters/', SitterListView.as_view(template_name='core/sitters.html'), name='sitters'),
]

offers/urls.py
from django.urls import path

from .views import (
    OfferListView,
    OfferAnswersListView,
    MakeOfferView,
)
from .views import (
    accept_offer_view,
    decline_offer_view
)


app_name = 'offers'
urlpatterns = [
    # ex: /offers/
    path('', OfferListView.as_view(), name='offers'),

    # ex: /offers/answers
    path('answers/', OfferAnswersListView.as_view(), name='answers'),

    # ex: /offers/1/
    path('<int:sitter_id>/', MakeOfferView.as_view(), name='make'),

    # ex: /offers/1/accept/
    path('accept/<int:offer_id>/', accept_offer_view, name='accept'),

    # ex: /offers/1/decline/
    path('decline/<int:offer_id>/', decline_offer_view, name='decline'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}

    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicons/site.webmanifest' %}">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    
    <title>Business Doggies{% block title %}{% endblock title %}</title>
</head>
<body>
    <div id="content" class="wrapper">
        {% if user.is_authenticated %}
            <div class="calentito container">
                <a href="{% url 'core:index' %}" class="nav-link logo">Business Doggies</a>
                <nav class="nav nav-logo">
                    {% block header %}
                        {% if user.is_client %}
                            <a href="{% url 'core:sitters' %}" class="nav-link sitter-link">Find Sitter</a>
                            <a href="{% url 'offers:offers' %}" class="nav-link">Proposals</a>
                            <a href="{% url 'offers:answers' %}" class="nav-link">Answers</a>
                        {% elif user.is_sitter %}
                            <a href="{% url 'offers:offers' %}" class="nav-link">Offers</a>
                            <a href="{% url 'offers:answers' %}" class="nav-link">Answered</a>
                        {% elif user.is_superuser %}
                            <a href="{% url 'admin:index' %}" class="nav-link logout-link">Admin</a>
                        {% endif %}
                    {% endblock header %}

                    {% block name %}
                        <a href="{% url 'accounts:profile' %}" class="nav-link {% if user.is_client %}client-link{% elif user.is_sitter %}sitter-link{% elif user.is_superuser %}admin-link{% endif %}">
                            {% if user.get_full_name %}
                                {{ user.get_full_name }}
                            {% else %}
                                {{ user.email }}
                            {% endif %}
                        </a>
                    {% endblock name %}
                </nav>
            </div>
            {% block hr %}
                {% if user.is_client %}
                    <hr class="hr-client">
                {% elif user.is_sitter %}
                    <hr class="hr-sitter">
                {% elif user.is_superuser %}
                    <hr class="hr-admin">
                {% endif %}
            {% endblock hr %}
        {% else %}
            <div class="calentito container">
                <a href="{% url 'core:index' %}" class="nav-link">Business Doggies</a>
                <nav class="nav nav-logo">
                    <a href="{% url 'accounts:login' %}" class="nav-link">Log In</a>
                </nav>
            </div>
        {% endif %}
            
        {% block content %}{% endblock content %}
    
    
    </div>
    <div>
        {% if user.is_client %}
            <hr class="hr-client m-0">
        {% elif user.is_superuser %}
            <hr class="hr-admin m-0">
        {% else %}
            <hr class="hr-sitter m-0">
        {% endif %}
        <div id="footer" class="container d-flex align-items-center justify-content-between">
            <span>Developed by the team <a href="https://github.com/ShviXXL/business-doggies"> IT-Котики </a></span>
            <span>Copyright &copy; Business Doggies 2020</span>
        </div>
    </div>
</body>
</html>